Repository Nullptr-Studios/Project-Hotline, pull requests merged in 2024-11, with the labels that each got.

#233 Game art
  Artwork/Enviroment/T_Dynamics.ase
  Artwork/Enviroment/T_Floors.ase
  Artwork/Enviroment/T_PropsAlleyways.ase
  Artwork/Enviroment/T_PropsClub.ase
  Artwork/Enviroment/T_PropsHouse.ase
  Artwork/Enviroment/T_PropsMetro.ase
  Artwork/Enviroment/T_PropsMotel.ase
  Artwork/Enviroment/T_PropsOffice.ase
  Artwork/Enviroment/T_PropsStorage.ase
  Artwork/Enviroment/T_Walls_Concrete.ase
  Artwork/Enviroment/T_Walls_Exterior.ase
  Artwork/Enviroment/T_Walls_Wood.ase
  Artwork/TilesetTemplate.ase
  Assets/Enviroment/Alleyway.meta
  Assets/Enviroment/Alleyway/M_WallsBuidling_Exterior.mat
  Assets/Enviroment/Alleyway/M_WallsBuidling_Exterior.mat.meta
  Assets/Enviroment/Alleyway/T_WallsBuildings_Exterior_Rim.png
  Assets/Enviroment/Alleyway/T_WallsBuildings_Exterior_Rim.png.meta
  Assets/Enviroment/Alleyway/T_WallsBuildings_Exterior_Rim_N.png
  Assets/Enviroment/Alleyway/T_WallsBuildings_Exterior_Rim_N.png.meta
  Assets/Scenes/Debug/SpriteTest.unity
  Assets/Scenes/Debug/SpriteTest.unity.meta
Labels: Art - Asset

#258 Act I Scenes
  Assets/Enemy/Alleyway/EB_Alley1.asset
  Assets/Enemy/Alleyway/EB_Alley1.asset.meta
  Assets/Enemy/Alleyway/EB_Alley2.asset
  Assets/Enemy/Alleyway/EB_Alley2.asset.meta
  Assets/Enemy/Alleyway/EB_Alley3.asset
  Assets/Enemy/Alleyway/EB_Alley3.asset.meta
  Assets/Enemy/Alleyway/EB_Alley4.asset
  Assets/Enemy/Alleyway/EB_Alley4.asset.meta
  Assets/Enemy/Enemy.prefab
  Assets/Enemy/Metro.meta
  Assets/Enemy/Metro/EB_Metro1.asset
  Assets/Enemy/Metro/EB_Metro1.asset.meta
  Assets/Enemy/Metro/EB_Metro2.asset
  Assets/Enemy/Metro/EB_Metro2.asset.meta
  Assets/Enemy/Metro/EB_Metro3.asset
  Assets/Enemy/Metro/EB_Metro3.asset.meta
  Assets/Enemy/Metro/EB_Metro4.asset
  Assets/Enemy/Metro/EB_Metro4.asset.meta
  Assets/Enemy/Metro/EB_Metro5.asset
  Assets/Enemy/Metro/EB_Metro5.asset.meta
  Assets/Enemy/Office.meta
  Assets/Enemy/Office/EB_Office1.asset
  Assets/Enemy/Office/EB_Office1.asset.meta
  Assets/Enemy/Office/EB_Office2.asset
  Assets/Enemy/Office/EB_Office2.asset.meta
  Assets/Enemy/Office/EB_Office3.asset
  Assets/Enemy/Office/EB_Office3.asset.meta
  Assets/Enviroment/PA_Tilemap.prefab
  Assets/Enviroment/TrainSpawner.cs
  Assets/Enviroment/TrainSpawner.cs.meta
  Assets/Scenes/Act1/Alleyways_Floor1.unity
  Assets/Scenes/Act1/Alleyways__Main.meta
  Assets/Scenes/Act1/Alleyways__Main.unity
  Assets/Scenes/Act1/Alleyways__Main/NavMesh-NavMesh.asset
  Assets/Scenes/Act1/Alleyways__Main/NavMesh-NavMesh.asset.meta
  Assets/Scenes/Act1/Metro_Floor1.unity
  Assets/Scenes/Act1/Metro_Floor2.unity
  Assets/Scenes/Act1/Metro__Main.meta
  Assets/Scenes/Act1/Metro__Main.unity
  Assets/Scenes/Act1/Metro__Main/NavMesh-NavMesh.asset
  Assets/Scenes/Act1/Metro__Main/NavMesh-NavMesh.asset.meta
  Assets/Scenes/Act1/Skyscraper_Floor1.unity
  Assets/Scenes/Act1/Skyscraper_Floor2.unity
  Assets/Scenes/Act1/Skyscraper__Main.meta
  Assets/Scenes/Act1/Skyscraper__Main.unity
  Assets/Scenes/Prototype/DemoScene.meta
  Assets/Scenes/Prototype/DemoScene.unity
  Assets/Scenes/Prototype/DemoScene/NavMesh-NavMesh.asset
  Assets/Scenes/Prototype/DemoScene/NavMesh-NavMesh.asset.meta
  fmod_editor.log
Labels: Design

#264 Optimization pass
  Assets/Civilian/Civilian.prefab
  Assets/Civilian/CivilianController.cs
  Assets/Civilian/CivilianDamageable.cs
  Assets/Core/Managers/ResourceManager.cs
  Assets/EmmiterHandler.cs
  Assets/EmmiterHandler.cs.meta
  Assets/Enemy/Containers.meta
  Assets/Enemy/EnemyDamageable.cs
  Assets/GotoHearingLocation.cs
  Assets/KriptoFX/MuzzleFlashes/Prefab/Impacts/GlassImpact.prefab
  Assets/KriptoFX/MuzzleFlashes/Prefab/Impacts/MetalImpact.prefab
  Assets/KriptoFX/MuzzleFlashes/Prefab/Impacts/WoodImpact.prefab
  Assets/KriptoFX/MuzzleFlashes/Prefab/MuzzleFlashes/Mobile/MuzzleFlash2.prefab
  Assets/Player/CS_PlayerHealth.cs
  Assets/Player/PlayerWeaponManager.cs
  Assets/Scenes/Act1/Alleyways__Main.unity
  Assets/Scenes/Act2/Mansion__Main  2.unity.meta
  Assets/Scenes/PlayerSprTesting.unity
  Assets/VFX/DynamicBlood/Blood Config.asset
  Assets/VFX/DynamicBlood/BloodManager.cs
  Assets/VFX/DynamicBlood/BloodManager_Pref.prefab
  Assets/VFX/DynamicBlood/FloorSplatter.cs
  Assets/VFX/DynamicBlood/FloorSplatterDissapear.cs
  Assets/VFX/DynamicBlood/Sprites/Blood.aseprite
  Assets/VFX/DynamicBlood/Sprites/Blood.aseprite.meta
  Assets/Weapons/FireWeapon.cs
  Assets/Weapons/MuzzleLightController.cs
  Assets/Weapons/Weapon.cs
  fmod_editor.log
Labels: Programming

#266 Bat Assasination
  Assets/Core/CameraController.cs
  Assets/Core/SceneManager/SceneData.cs
  Assets/Core/SceneManager/SceneMngr.cs
  Assets/Core/TheKiwiCoder/BehaviourTree/Scripts/Actions/SensePlayer.cs
  Assets/Core/VNEventTrigger.cs
  Assets/Core/VNEventTrigger.cs.meta
  Assets/Enemy/Corpse Config.asset
  Assets/Enemy/Enemy Behaviour Data.asset
  Assets/Enemy/Enemy.prefab
  Assets/Enemy/EnemyDamageable.cs
  Assets/Enemy/Sprite/EnemyTorso.controller
  Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset
  Assets/Scenes/Act1/Alleyways__Main.unity
  Assets/Weapons/MD_LongMelee.asset
  Assets/Weapons/MD_ShortMelee.asset
  Assets/Weapons/Weapon.cs
  fmod_editor.log
Labels: Art - Asset, Programming

#272 Remove reload
  Assets/Civilian/CivilianController.cs
  Assets/Core/IA_InputActions.cs
  Assets/Core/IA_InputActions.inputactions
  Assets/Core/SceneManager/SceneMngr.cs
  Assets/Core/TheKiwiCoder/BehaviourTree/Scripts/Actions/LookForNearestWeapon.cs
  Assets/Core/TheKiwiCoder/BehaviourTree/Scripts/Actions/SensePlayer.cs
  Assets/Enemy/Enemy.prefab
  Assets/Enemy/EnemyBehaviourTree.asset
  Assets/GotoHearingLocation.cs
  Assets/Player/PlayerMovement.cs
  Assets/Player/PlayerWeaponManager.cs
  Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset
  Assets/Scenes/PlayerSprTesting.unity
  Assets/UI/CS_AmmoPrompt.cs
  Assets/Weapons/FireWeapon.cs
  fmod_editor.log
Labels: Programming

#273 Beta fixes
  Assets/Core/TheKiwiCoder/BehaviourTree/Scripts/Actions/SensePlayer.cs
  Assets/MissionTrigger/PA_LevelManager.prefab
  Assets/Scenes/Act1/Alleyways__Main.unity
  Assets/Scenes/Act1/Metro_Floor1.unity
  Assets/Scenes/Act1/Metro_SceneData.asset
  Assets/Scenes/Act1/Metro__Main.unity
  Assets/Scenes/Act1/Skyscraper_SceneData.asset
  Assets/Scenes/Act1/Skyscraper__Main.unity
  Assets/Scenes/Act1/Tutorial_SceneData.asset
  Assets/Scenes/Act2/Mansion__Main.unity
  Assets/Scenes/UI/MainMenu.unity
  Assets/UI/CS_MainMenu.cs
  Assets/Weapons/WD_Pistol.asset
  ProjectSettings/ProjectSettings.asset
Labels: Design, Programming
